Fix link errors with USE_DOUBLE_BUFFERING because of wrong inline definition
In DisplayDriver.h from MLA installation "extern inline" was used
instead of "static inline" for InvalidateAll() and
IsDisplayUpdatePending().

Apparently an older GCC version tolerated that code, there were no link
errors at that time (January 2015, GCC 4.9.2). Now GCC 10.2.0 has been
used.

Modified DisplayDriver.h will be created in GENERATED_DIR/Graphics/,
Graphics.h will only be copied to GENERATED_DIR/Graphics/ to include the
corrected DisplayDriver.h.

Only MLA_INSTALL_PATH/Microchip/Include/Graphics/ added as include
search path, GENERATED_DIR/Graphics/ not.
Files included by Graphics/Graphics.h without "Graphcis/" prepended in
the #include directive will first be tried from GENERATED_DIR/Graphics/,
then from MLA_INSTALL_PATH/Microchip/Include/Graphics/.

'#include "Graphics/DisplayDriver.h"' instead of '#include
"DisplayDriver.h"' in Graphics/Graphics.h would have helped without the
need to copy that file to GENERATED_DIR/Graphics/.

Projects with the link errors:
- Object Layer
- PIC32LCC
- any other demo project or the example when defining USE_DOUBLE_BUFFERING

Extract from linker error messages:
/usr/bin/ld: build_ObjectLayer/generated_ObjectLayer/Button.o: in function `InvalidateAll':
/opt/microchip_solutions/Microchip/Include/Graphics/DisplayDriver.h:696: multiple definition of `InvalidateAll'; build_ObjectLayer/DemoProjects_compat.o:/opt/microchip_solutions/Microchip/Include/Graphics/DisplayDriver.h:696: first defined here
/usr/bin/ld: build_ObjectLayer/generated_ObjectLayer/Button.o: in function `IsDisplayUpdatePending':
/opt/microchip_solutions/Microchip/Include/Graphics/DisplayDriver.h:724: multiple definition of `IsDisplayUpdatePending'; build_ObjectLayer/DemoProjects_compat.o:/opt/microchip_solutions/Microchip/Include/Graphics/DisplayDriver.h:724: first defined here